export const FETCH_STORYIDS = 'FETCH_STORYIDS'
export const FETCH_STORYIDS_SUCCESS = 'FETCH_STORYIDS_SUCCESS'
export const FETCH_STORIES = 'FETCH_STORIES'
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
